from __future__ import unicode_literals

from django.conf import settings
from selenium.webdriver.firefox.webdriver import WebDriver


def get(key, default):
    return getattr(settings, key, default)


DJANGO_WEBDRIVER_CLASS = get('DJANGO_WEBDRIVER_CLASS', WebDriver)
DJANGO_WEBDRIVER_KWARGS = get('DJANGO_WEBDRIVER_KWARGS', {})
DJANGO_WEBDRIVER_IMPLICITLY_WAIT = get('DJANGO_WEBDRIVER_IMPLICITLY_WAIT', 4)
DJANGO_WEBDRIVER_IMPLICITLY_WAIT_QUICK_ASSERT = get('DJANGO_WEBDRIVER_IMPLICITLY_WAIT_QUICK_ASSERT', 1)
DJANGO_WEBDRIVER_GOTO_DELAY = get('DJANGO_WEBDRIVER_GOTO_DELAY', 0)
DJANGO_WEBDRIVER_PER_COMMAND_DELAY = get('DJANGO_WEBDRIVER_PER_COMMAND_DELAY', 0)
DJANGO_WEBDRIVER_SCREENSHOT_PATH = get('DJANGO_WEBDRIVER_SCREENSHOT_PATH', '')
